** Data Scripts for IBS Bank - Batch 7 - Group 3 **


DROP DATABASE IF EXISTS IBSG3;

CREATE DATABASE IBSG3;

USE IBSG3;

CREATE TABLE KYC_DETAILS(
REG_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
GENDER CHAR(1),
DOB DATE,
EMAIL_ID VARCHAR(50),
MOBILE_NUM VARCHAR(10),
ADDRESS VARCHAR(100),
CITY VARCHAR(20),
PINCODE INT,
TYPE_OF_ACCT_HOLDER VARCHAR(20),
CUST_ACCT_TYPE VARCHAR(20),
KYC_IDENTITY_PROOF VARCHAR(20),
KYC_PROOF_DOC VARCHAR(100),
KYC_UPLOAD_IND CHAR(1),
ADMIN_COMMENTS_KYC VARCHAR(20),
KYC_APPROVAL_STATUS VARCHAR(1),
CREATED_DT DATE,
MODIFIED_DT DATE
);
ALTER TABLE KYC_DETAILS AUTO_INCREMENT = 101;



CREATE TABLE CUST_ACCT(
UCI INT NOT NULL PRIMARY KEY AUTO_INCREMENT, FOREIGN KEY (REG_ID) REFERENCES KYC_DETAILS(REG_ID),
REG_ID INT,
CUST_ACCT_NUM INT UNIQUE KEY,
CUST_NAME  VARCHAR(50),
CUST_ACCT_TYPE VARCHAR(20),
AVLBL_BAL DECIMAL(10,2),
ACCT_START_DATE DATE,
ACCT_CLOSE_DATE DATE,
BRANCH_NAME VARCHAR(30),
BRANCH_IFSC_CODE VARCHAR(10),
INTEREST_RATE_PCT INT,
CUST_ACCT_STATUS VARCHAR(20),
CREATED_DT DATE
);
ALTER TABLE CUST_ACCT AUTO_INCREMENT = 1000000000000001;


CREATE TABLE CUST_BNFCRY(
BNFCRY_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
CUST_ACCT_NUM INT,
FOREIGN KEY (CUST_ACCT_NUM) REFERENCES CUST_ACCT(CUST_ACCT_NUM),
BNFCRY_ACCT_NUM INT,
BNFCRY_ACCT_NAME VARCHAR(50),
BNFCRY_BANK_NAME VARCHAR(50),
BNFCRY_ACCT_IFSC VARCHAR(10),
BNFCRY_TXN_TYP VARCHAR(10),
BNFCRY_MOBILE_NUM VARCHAR(50),
CREATED_DT DATE
);
ALTER TABLE CUST_BNFCRY AUTO_INCREMENT = 111;


CREATE TABLE CUST_ACCT_TXN_INFO(
TXN_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FOREIGN KEY (CUST_ACCT_NUM) REFERENCES CUST_ACCT(CUST_ACCT_NUM),
CUST_ACCT_NUM INT,
CUST_ACCT_TYPE VARCHAR(20),
TXN_TYPE VARCHAR(10),
FROM_ACCT_NUM INT,
TO_ACCT_NUM INT,
TXN_AMT DECIMAL(10,2),
TXN_DATE_TIME TIMESTAMP,
TXN_COMMENTS VARCHAR(200),
CREATED_DT DATE
);
ALTER TABLE CUST_ACCT_TXN_INFO AUTO_INCREMENT = 111;


CREATE TABLE SERVICE_PROVIDER(
SERVICE_PROVIDER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
REG_ID INT,
SERVICE_PROVIDER_NAME  VARCHAR(100),
BANK_NAME VARCHAR(100),
ACCOUNT_ID VARCHAR(50),
BRANCH_NAME VARCHAR(100),
IFSC_CODE  VARCHAR(100),
SVC_START_DATE DATE,
SVC_END_DATE DATE,
CRAETED_DT DATE,
FOREIGN KEY (REG_ID) REFERENCES KYC_DETAILS(REG_ID)
);

CREATE TABLE LOGIN_PASSWORD(
LOGIN_SQE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
LOGIN_ID INT,
LOGIN_TYPE VARCHAR(20),
LOGIN_PWD VARCHAR(20),
TXN_PWD VARCHAR(20),
SECURITY_QUES1 VARCHAR(50),
SECURITY_ANS1 VARCHAR(10),
CREATED_DT DATE 
);

CREATE TABLE INTEREST_RATES (
INTEREST_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
INTEREST_TYPE VARCHAR(20),
INTEREST_TENURE VARCHAR(20),
INTEREST_RATE_PCT INT,
CREATED_DT DATE,
MODIFIED_DT DATE
);

/***************************** Tables not in scope now **************************************/

CREATE TABLE CUST_LOAN_LOAN_REQ(
LOAN_REQ_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
LOAN_TYPE   VARCHAR(50),
CUST_ACCT_NUM INT,
LOAN_AMT_REQUESTED DECIMAL(10,2),
LOAN_APPROVAL_STATUS  VARCHAR(20),
ADMIN_COMMENT_LOAN  VARCHAR(200),
CREATED_DT DATE,
FOREIGN KEY (CUST_ACCT_NUM) REFERENCES CUST_ACCT(CUST_ACCT_NUM)
);

CREATE TABLE CUST_LOAN_DETAILS(
LOAN_NUM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
LOAN_REQ_ID INT, 
LOAN_AMOUNT DECIMAL(10,2),
LOAN_START_DATE DATE,
LOAN_END_DATE DATE,
LOAN_TENURE_MNTHS INT,
LOAN_INTEREST_RATE DECIMAL(10,2),
LOAN_EMI_AMT DECIMAL(10,2),
LOAN_EMI_DATE DATE,
CREATED_DT DATE,
FOREIGN KEY (LOAN_REQ_ID) REFERENCES CUST_LOAN_LOAN_REQ(LOAN_REQ_ID)
);

CREATE TABLE LOAN_PAYMENTS(
LOAN_EMI_PAYMENT INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
LOAN_NUM INT,
LOAN_PAYMENTS_DATE DATE,
CAPITAL_PAID DECIMAL(10,2),
INTEREST_PAID DECIMAL(10,2), 
PAYMENT_MODE VARCHAR(50),
LOAN_OUTSTANDING_AMT DECIMAL(10,2),
PER_CLOSURE_ELIGIBILITY VARCHAR(50),
PRE_CLOSURE_DTE DATE,
FOREIGN KEY (LOAN_NUM) REFERENCES CUST_LOAN_DETAILS(LOAN_NUM)
);

CREATE TABLE CUST_DEBIT_CREDIT_CARD_REQ(
CARD_REQ_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FOREIGN KEY (CUST_ACCT_NUM) REFERENCES CUST_ACCT(CUST_ACCT_NUM),
CARD_TYPE  VARCHAR(10),
CUST_ACCT_NUM INT,
CARD_APPROVAL_STATUS  VARCHAR(20),
ADMIN_COMMENTS_CARD VARCHAR(200),
CREATED_DT DATE
);

CREATE TABLE CUST_CARD_DETAILS(
CARD_NUM INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
FOREIGN KEY (CUST_ACCT_NUM) REFERENCES CUST_ACCT(CUST_ACCT_NUM),
CARD_TYPE VARCHAR(10),
CARD_NAME VARCHAR(30),
CUST_ACCT_NUM INT,
CARD_CVV INT,
CARD_PIN INT,
CARD_EXPIRY VARCHAR(10),
CARD_STATUS VARCHAR(10),
CARD_UPGRADE_AVLBL_TO VARCHAR(20), 
CREDIT_CARD_LIMIT Double(10,2),
CARD_CASHBACK_PTS INT,
CREATED_DT DATE
);


CREATE TABLE CUST_CARD_TXN_INFO(
CARD_TXN_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
CARD_NUM INT,
CARD_TXN_AMT DECIMAL(10,2),
TXN_DATE_TIME TIMESTAMP,
FROM_ACCT_NUM  INT, 
TO_ACCT_NUM INT,
CARD_TXN_COMMENTS VARCHAR(200),
CREATED_DT DATE,
FOREIGN KEY (CARD_NUM) REFERENCES CUST_CARD_DETAILS(CARD_NUM)
);
